## Introduction à Pandas

Pandas est une librairie Python spécialisée dans l’analyse des données. Il nous permet de faire des opérations efficaces sur des données sous forme de tableaux multidimensionnels homogènes.

In [112]:
import numpy as np
import pandas as pd

### Series
Series  de Pandas est une généralisation d'un ndarray de NumPy d'une seule dimension. Sa particularité est que les valeurs sont indexées.

In [113]:
x = np.random.random(4)
x

array([0.99244592, 0.23150473, 0.37339235, 0.73936458])

In [114]:
x = pd.Series(x)
x

0    0.992446
1    0.231505
2    0.373392
3    0.739365
dtype: float64

In [115]:
x[0]

np.float64(0.9924459230998984)

Les index peuvent être non numériques.

In [116]:
si = pd.Series([210, 31, 40, 15],index =['Porcupine','Chipmunk','Squirrel','Goat'])
si

Porcupine    210
Chipmunk      31
Squirrel      40
Goat          15
dtype: int64

In [117]:
si['Porcupine']

np.int64(210)

In [118]:
si[0] #mais cette façon d'indexer reste toujours valide

KeyError: 0

Series a tous les avantages donnés par ndarray de Numpy.

### Structure DataFrame
DataFrame est celui qui nous intéresse le plus dans la librairie Pandas. Une matrice DataFrame correspond à une matrice individus-variables où les lignes correspondent à des observations, les
colonnes à des attributs décrivant les individus. Chaque colonne est de type Series.

On peut créer un DataFrame de plusieurs façons:
- à partir d'un fichier ( texte, csv, excel , ...)
- à partir d'un dictionnaire, liste ou tuples
- à partir de Series de Pandas, array de Numpy

In [119]:
import numpy as np
import pandas as pd
#la création manuelle d'un dataframe qui passe par un dictionnaire
data = {'city': [ 'Boston', 'Paris', 'Lagos' ],'area': [ 11700, 17174, 2706],'population': [4628910, 12405426, 21000000]}
frame = pd.DataFrame(data)
print(frame)
#la creation manuelle d'un DataFrame qui passe par Numpy 
df2 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),columns=['col1', 'col2', 'col3'])
df2

     city   area  population
0  Boston  11700     4628910
1   Paris  17174    12405426
2   Lagos   2706    21000000

   col1  col2  col3
0     1     2     3
1     4     5     6
2     7     8     9

Quelques opérations élémentaires sur un DataFrame

In [120]:
print(frame.columns) #permet d'avoir les columns de frame
type(frame.columns)

Index(['city', 'area', 'population'], dtype='str')

pandas.Index

In [121]:
frame.city #equivalent à frame['city'], permet de prendre la colonne entière city

0    Boston
1     Paris
2     Lagos
Name: city, dtype: str

In [122]:
frame.loc[0] #get row with index 0

city           Boston
area            11700
population    4628910
Name: 0, dtype: object

In [123]:
frame.loc[0:2]['city'] #combinaison des deux avec un bonus slicing

0    Boston
1     Paris
2     Lagos
Name: city, dtype: str

In [124]:
frame.population.max() #population maximale
frame[frame.population == frame.population.max()].city #le city ayant la population maximale

2    Lagos
Name: city, dtype: str

In [125]:
frame

     city   area  population
0  Boston  11700     4628910
1   Paris  17174    12405426
2   Lagos   2706    21000000

In [126]:
frame.loc[0,'population']=21000000 #modification de valeurs

In [127]:
frame

     city   area  population
0  Boston  11700    21000000
1   Paris  17174    12405426
2   Lagos   2706    21000000

In [128]:
frame[['city','area']] #pour prendre deux colonnes

     city   area
0  Boston  11700
1   Paris  17174
2   Lagos   2706

In [129]:
frame.loc[0:2][['city','area']] #combinaison

     city   area
0  Boston  11700
1   Paris  17174
2   Lagos   2706

select city,population from frame

In [130]:
frame[['city','area']].loc[0:2] #même resultat que ci-dessus

     city   area
0  Boston  11700
1   Paris  17174
2   Lagos   2706

## Ajouter une ligne dans un DataFrame

In [131]:
dfTemp = pd.DataFrame({'city':['Kiev'],'area': [110000],'population':[1075000]})

In [132]:
frame = pd.concat([frame,dfTemp],ignore_index=True)

In [133]:
frame

     city    area  population
0  Boston   11700    21000000
1   Paris   17174    12405426
2   Lagos    2706    21000000
3    Kiev  110000     1075000

On peut effacer un enregistrement en indiquant les lignes à effacer, on utilise la méthode drop. Attention la fonction drop ne modifie pas directement l'objet dataFrame mais elle renvoie un nouvel objet dataFrame avec l'élément éffacé.

In [134]:
frame

     city    area  population
0  Boston   11700    21000000
1   Paris   17174    12405426
2   Lagos    2706    21000000
3    Kiev  110000     1075000

## Ajouter une colonne

In [135]:
dfTemp2 = pd.DataFrame({'country':[]})

In [136]:
frame= pd.concat([frame,dfTemp2],ignore_index=True)

## Effacer ligne ou colonne

In [137]:
frame.drop([1], axis=0) #attention ceci n'affecte pas frame mais renvoie un nouveau Dataframe

     city      area  population  country
0  Boston   11700.0  21000000.0      NaN
2   Lagos    2706.0  21000000.0      NaN
3    Kiev  110000.0   1075000.0      NaN

In [138]:
frame.drop(['city'], axis=1)

       area  population  country
0   11700.0  21000000.0      NaN
1   17174.0  12405426.0      NaN
2    2706.0  21000000.0      NaN
3  110000.0   1075000.0      NaN

### Equivalence SQL, DataFrame

DataFrame est en quelques sortes un SGBD comme Mysql. Les requetes SQL ont des équivalences en DataFrame.
Par exemple , soit la requete SQL suivant :

SELECT city FROM frame where population>=4000000

Son équivalence en DataFrame est

In [139]:
frame[frame['population']>4000000]['city']

0    Boston
1     Paris
2     Lagos
Name: city, dtype: str

Par exemple aussi:
    
SELECT city,area FROM frame where population>=4000000

In [140]:
frame[frame['population']>=4000000][['city','area']]

     city     area
0  Boston  11700.0
1   Paris  17174.0
2   Lagos   2706.0

Ou encore:

SELECT city,area FROM frame where population>=4000000 limit 1

In [141]:
frame[frame['population']>=4000000][['city','area']][0:1]

     city     area
0  Boston  11700.0

ou encore

SELECT count(*) FROM frame

In [142]:
frame.shape[0]

4

ou encore

SELECT sum(population) FROM frame

In [143]:
frame['population'].sum()

np.float64(55480426.0)

ou encore 

SELECT * from frame where country IS NULL

In [144]:
frame.loc[frame['country'].isna()]

     city      area  population  country
0  Boston   11700.0  21000000.0      NaN
1   Paris   17174.0  12405426.0      NaN
2   Lagos    2706.0  21000000.0      NaN
3    Kiev  110000.0   1075000.0      NaN

ou encore 

UPDATE frame SET  country = 'mada'
WHERE country is NULL

In [145]:
frame['country']= frame['country'].fillna("mada")

In [146]:
frame

     city      area  population country
0  Boston   11700.0  21000000.0    mada
1   Paris   17174.0  12405426.0    mada
2   Lagos    2706.0  21000000.0    mada
3    Kiev  110000.0   1075000.0    mada

### Exercices
Faire les equivalences des requetes suivantes

1) `SELECT * from frame where area is not null`

In [147]:
frame[frame['area'].isna() == False]

     city      area  population country
0  Boston   11700.0  21000000.0    mada
1   Paris   17174.0  12405426.0    mada
2   Lagos    2706.0  21000000.0    mada
3    Kiev  110000.0   1075000.0    mada

2) `SELECT city, country from frame where population>2000000`

In [148]:
frame[frame['population'] > 2000000][['city', 'country']]

     city country
0  Boston    mada
1   Paris    mada
2   Lagos    mada

3) `Delete from frame where city='Lagos'`

In [149]:
frame.drop(frame[frame['city'] == 'Lagos'].index)

     city      area  population country
0  Boston   11700.0  21000000.0    mada
1   Paris   17174.0  12405426.0    mada
3    Kiev  110000.0   1075000.0    mada

4) `Insert into frame(city,population,population) values('tana',5000000,'Mada')`

In [150]:
mada = pd.DataFrame({'city': ['Tana'], 'population': [5000000], 'country': ['mada']})
frame = pd.concat([frame, mada], ignore_index = True)
frame

     city      area  population country
0  Boston   11700.0  21000000.0    mada
1   Paris   17174.0  12405426.0    mada
2   Lagos    2706.0  21000000.0    mada
3    Kiev  110000.0   1075000.0    mada
4    Tana       NaN   5000000.0    mada

5) `select city from frame where city like %o%`

In [153]:
frame[frame['city'].str.contains('o')][['city']]

     city
0  Boston
2   Lagos

6) `select * from frame where population>10000000 and area>4000`

In [156]:
frame[(frame['population'] > 10000000) & (frame['area'] > 4000)]

     city     area  population country
0  Boston  11700.0  21000000.0    mada
1   Paris  17174.0  12405426.0    mada

7) select city from frame order by population,city

In [158]:
frame.sort_values(['population', 'city'])['city']

3      Kiev
4      Tana
1     Paris
0    Boston
2     Lagos
Name: city, dtype: str

8) select country,sum(population) from city group by country

In [162]:
frame.groupby('country')['population'].sum()

country
mada    60480426.0
Name: population, dtype: float64

### Lecture de fichier avec pandas

On peut lire un fichier texte brute, csv et excel en utilisant respectivement les fonctions
pd.read_table, pd.read_csv, pd.read_excel.